site_name: qtstrap
site_description: 'qtstrap docs'
site_author: 'David Kincaid'
docs_dir: docs/
repo_name: 'qtstrap/qtstrap'
repo_url: 'https://github.com/qtstrap/qtstrap'
theme:
    name: readthedocs
nav:
    - Home: index.md
    - Installation: installation.md
    - Widgets: widgets.md
