site_name: qtstrap
site_description: 'qtstrap docs'
site_author: 'David Kincaid'
docs_dir: docs/
repo_name: 'qtstrap/qtstrap'
repo_url: 'https://github.com/qtstrap/qtstrap'
theme:
    name: readthedocs
nav:
    - Overview: index.md
    - Installation: installation.md
    - Getting Started: gettingstarted.md
    - Project Structure: 
        - Project Structure: structure/structure.md
        - Makefile: structure/makefile.md
    # - Widgets: 
    #     - Base Application: widgets/baseapplication.md
    #     - Base Main Window: widgets/basemainwindow.md
